name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        py-version: ['3.10', 3.11, 3.12]
        exclude:
          - os: macos-14
            py-version: 3.11
    steps:
    - name: Set up Python on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}
        




